### ISSUE TITLE
Feedback 1

### ISSUE THREAD

**Issue by bursteinalan** [CS521-2022-SC1/final-project-DeDe-Sunshine#1]
- Extraneous files (.idea, .ipynb_checkpoints, .DS_Store) .gitnore.txt should be .gitignore (spelling and no .txt, use PyCharm to create it to ensure no extension)
- Good start
- Remember to take a sec to actually take a look at the data, visualize a few of the data points (ie the images themselves as data) and try to get some summaries of each category (for example start with just the count)
- Deliverable met

**Comment by DeDe-Sunshine** [comment]
So far, the task of cutting each image in half, saving in same directory (so re-using code would be easier) then moving original files to a different directory took a long time due to many errors and having to find workaround.  i finally got this accomplished on Sunday.  Will try to do the rest Sunday Night and Monday.  

VGG16 remain one of the best to try.
MobileNet will be another one to try.
